CREATE TABLE feed (
	id INT AUTO_INCREMENT PRIMARY KEY,
	url VARCHAR(256) UNIQUE NOT NULL,
	last_pub_date DATETIME
) ENGINE MYISAM;

CREATE TABLE article (
	id BIGINT AUTO_INCREMENT PRIMARY KEY,
	url VARCHAR(256) UNIQUE NOT NULL,
	pub_date TIMESTAMP,
	txt MEDIUMTEXT,
	feed_id INT NOT NULL,
	CONSTRAINT article_to_feed FOREIGN KEY (feed_id) REFERENCES feed(id)
) ENGINE MYISAM;